project_id = "mugunkyfvdpwiedjqgil"

[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.createStripeCheckoutSession]
verify_jwt = true

[functions.verifyStripeCheckoutSession]
verify_jwt = true

[functions.createPayPalOrder]
verify_jwt = false

[functions.capturePayPalOrder]
verify_jwt = true

[functions.createStripeSubscription]
verify_jwt = true

[functions.createCustomerPortalSession]
verify_jwt = true

[functions.stripeWebhook]
verify_jwt = false
